### ISSUE TITLE
Add demo for Console logger in GUI app

### ISSUE THREAD

**Issue by TommiPrami** [danieleteti/loggerpro#16]
Tried it, and allocated the Console, but did not see anything in the Console.

There must be some hoops I should jump through to get it working properly.

That would be very nice way to "debug" things on different computers (if not remote debugging possibilities), so really would like to test that and get it to working.

**Comment by Fulgan** [comment]
Here is a new version of the ConsoleAppender class that creates a new console if none is present.

It also works from the command line (although since LoggerPro is multithreaded, you'll end up with messages printed in the wrong order)

[LoggerPro.ConsoleAppenderEx.pas.zip](https://github.com/danieleteti/loggerpro/files/2266714/LoggerPro.ConsoleAppenderEx.pas.zip)

**Comment by mWaltari** [comment]
Woohoo!

**Comment by danieleteti** [comment]
It Will be included in the next version. Thank you
